import { BOOKING_ERROR_CODES } from '../../../core/api-business.error';

export const PORTAL_AGENDA_LITERALS = {
  title: 'Agenda',
  subtitle: 'Pide cita en un hueco libre, cambia o anula la que tengas',
  loading: 'Cargando agenda…',
  noSession: 'No hay sesión de cliente.',
  loadError: 'No se ha podido cargar la agenda.',
  service: 'Servicio',
  trainer: 'Entrenador',
  allTrainers: 'Todos los entrenadores',
  slots: 'Huecos disponibles',
  emptySlots: 'No hay huecos para este servicio.',
  noService: 'Contrata un bono vigente con sesiones para poder reservar.',
  myAppointments: 'Mis citas',
  emptyAppointments: 'No tienes citas.',
  book: 'Reservar',
  change: 'Cambiar',
  cancel: 'Anular',
  saveChange: 'Guardar cambio',
  close: 'Cerrar',
  startsAt: 'Inicio',
  trainerName: 'Entrenador',
  status: 'Estado',
  statusPending: 'Pendiente de confirmación',
  statusConfirmed: 'Confirmada',
  statusCompleted: 'Realizada',
  statusCancelled: 'Anulada',
  categoryPersonal: 'Entrenamiento personal',
  categoryHipopresivos: 'Hipopresivos',
  categoryMasaje: 'Masaje',
  booked: 'Cita solicitada.',
  cancelled: 'Cita anulada.',
  errorCutoff: 'Fuera de plazo o el hueco no está disponible.',
  errorSlotTaken: 'Ese hueco ya está ocupado.',
  errorOneAppointment: 'Ya tienes una cita activa. Anúlala o cámbiala antes de pedir otra.',
  errorNotBookable: 'Este servicio lo agenda el estudio.',
  errorBonoRequired: 'Necesitas un bono vigente con sesiones.',
  errorExpiredBono: 'El bono está caducado.',
  errorNoSessions: 'No quedan sesiones.',
  errorInvalid: 'No se puede actualizar esta cita.',
  errorSave: 'No se ha podido guardar la cita.',
  errorServiceInactive: 'Este servicio no está activo.',
} as const;

export const PORTAL_BOOKING_ERROR_LITERALS: Record<string, string> = {
  [BOOKING_ERROR_CODES.cutoff]: PORTAL_AGENDA_LITERALS.errorCutoff,
  [BOOKING_ERROR_CODES.slotTaken]: PORTAL_AGENDA_LITERALS.errorSlotTaken,
  [BOOKING_ERROR_CODES.oneAppointment]: PORTAL_AGENDA_LITERALS.errorOneAppointment,
  [BOOKING_ERROR_CODES.serviceNotBookable]: PORTAL_AGENDA_LITERALS.errorNotBookable,
  [BOOKING_ERROR_CODES.bonoRequired]: PORTAL_AGENDA_LITERALS.errorBonoRequired,
  [BOOKING_ERROR_CODES.expiredBono]: PORTAL_AGENDA_LITERALS.errorExpiredBono,
  [BOOKING_ERROR_CODES.noSessions]: PORTAL_AGENDA_LITERALS.errorNoSessions,
  [BOOKING_ERROR_CODES.invalidStatus]: PORTAL_AGENDA_LITERALS.errorInvalid,
  [BOOKING_ERROR_CODES.serviceInactive]: PORTAL_AGENDA_LITERALS.errorServiceInactive,
};
