export const CLIENTS_LITERALS = {
  title: 'Clientes',
  subtitle: 'Fichas y seguimiento uno a uno',
  search: 'Buscar',
  searchPlaceholder: 'Nombre, email o teléfono',
  newClient: 'Nuevo cliente',
  edit: 'Editar',
  delete: 'Eliminar',
  empty: 'Sin clientes',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  email: 'Email',
  phone: 'Teléfono',
  notes: 'Notas',
  instantConfirm: 'Confirmación inmediata',
  yes: 'Sí',
  no: 'No',
  bonosTitle: 'Bonos contratados',
  remainingSessions: 'Sesiones restantes',
  expiresAt: 'Caducidad',
  noExpiry: 'Sin caducidad',
  editBono: 'Editar bono',
  emptyBonos: 'Sin bonos contratados',
  save: 'Guardar',
  back: 'Volver al listado',
  fichaTitle: 'Ficha del cliente',
  fichaNewTitle: 'Nuevo cliente',
  errorRequired: 'Completa los campos obligatorios.',
  errorLoad: 'No se ha podido cargar la ficha.',
  errorSave: 'No se ha podido guardar el cliente.',
  temporaryPassword: 'Contraseña temporal',
  temporaryPasswordHint: 'Entrégasela al cliente. Solo se muestra ahora.',
} as const;
