export const CLIENTS_LITERALS = {
  title: 'Clientes',
  subtitle: 'Personas del estudio: ficha, bonos y seguimiento',
  emptyTitle: 'Todavía no hay clientes',
  search: 'Buscar',
  searchPlaceholder: 'Nombre, email o teléfono',
  newClient: 'Nuevo cliente',
  edit: 'Editar',
  delete: 'Eliminar',
  empty: 'Sin clientes',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  email: 'Email',
  phone: 'Teléfono',
  notes: 'Notas',
  instantConfirm: 'Confirmación inmediata',
  yes: 'Sí',
  no: 'No',
  assignedTitle: 'Bonos asignados',
  remainingSessions: 'Sesiones restantes',
  expiresAt: 'Caducidad',
  noExpiry: 'Sin caducidad',
  service: 'Servicio',
  bono: 'Bono',
  sessions: 'Sesiones',
  price: 'Precio',
  editBono: 'Editar bono',
  emptyAssigned: 'Sin bonos asignados',
  giftTitle: 'Regalar',
  gift: 'Regalar',
  giftKind: 'Tipo',
  giftPack: 'Bono',
  giftSingle: 'Sesión suelta',
  singleSession: 'Sesión suelta',
  gifted: 'Regalo asignado.',
  giftError: 'No se ha podido asignar el regalo.',
  confirmGiftTitle: 'Regalar al cliente',
  confirmGiftPackMessage: 'Se asignará este bono al cliente.',
  confirmGiftSingleMessage: 'Se asignará una sesión suelta de este servicio.',
  unassign: 'Desasignar',
  unassigned: 'Bono desasignado.',
  confirmUnassignTitle: 'Desasignar bono',
  confirmUnassignMessage: 'Se quitará este bono del cliente.',
  errorAssigned: 'No se puede desasignar: el cliente tiene citas pendientes o confirmadas con este bono.',
  save: 'Guardar',
  back: 'Volver al listado',
  fichaTitle: 'Ficha del cliente',
  fichaNewTitle: 'Nuevo cliente',
  errorRequired: 'Completa los campos obligatorios.',
  errorLoad: 'No se ha podido cargar la ficha.',
  errorSave: 'No se ha podido guardar el cliente.',
  confirmDeleteTitle: 'Eliminar cliente',
  confirmDeleteMessage: 'Se eliminará este cliente y no se puede deshacer.',
  deleted: 'Cliente eliminado.',
  temporaryPassword: 'Contraseña temporal',
  temporaryPasswordHint: 'Entrégasela al cliente. Solo se muestra ahora.',
} as const;
