export const CLIENTS_LITERALS = {
  title: 'Clientes',
  subtitle: 'Fichas y seguimiento uno a uno',
  search: 'Buscar',
  searchPlaceholder: 'Nombre, email o teléfono',
  newClient: 'Nuevo cliente',
  edit: 'Editar',
  delete: 'Eliminar',
  empty: 'Sin clientes',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  email: 'Email',
  phone: 'Teléfono',
  notes: 'Notas',
  save: 'Guardar',
  back: 'Volver al listado',
  fichaTitle: 'Ficha del cliente',
  fichaNewTitle: 'Nuevo cliente',
  errorRequired: 'Completa los campos obligatorios.',
  errorLoad: 'No se ha podido cargar la ficha.',
  errorSave: 'No se ha podido guardar el cliente.',
} as const;
