export const CALENDAR_LITERALS = {
  title: 'Calendario',
  subtitle: 'Citas, entrenadores y horarios',
  loggedAs: 'Sesión',
  week: 'Semana',
  day: 'Día',
  newAppointment: 'Nueva cita',
  editAppointment: 'Editar cita',
  save: 'Guardar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  trainer: 'Entrenador',
  client: 'Cliente',
  service: 'Servicio',
  bono: 'Bono',
  startsAt: 'Inicio',
  endsAt: 'Fin',
  location: 'Lugar',
  locationPlaceholder: 'Sala o estudio',
  singleSession: 'Sesión suelta',
  errorRequired: 'Completa los campos obligatorios.',
  errorBonoRequired: 'Este servicio requiere un bono contratado.',
  errorSave: 'No se ha podido guardar la cita.',
  categoryPersonal: 'Entrenamiento personal',
  categoryHipopresivos: 'Hipopresivos',
  categoryMasaje: 'Masaje',
} as const;
