import { BOOKING_ERROR_CODES } from '../../core/api-business.error';

export const CALENDAR_LITERALS = {
  title: 'Calendario',
  subtitle: 'Citas, entrenadores y horarios',
  loggedAs: 'Sesión',
  week: 'Semana',
  day: 'Día',
  newAppointment: 'Nueva cita',
  editAppointment: 'Editar cita',
  save: 'Guardar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  confirm: 'Confirmar',
  complete: 'Marcar realizada',
  cancelAppointment: 'Anular cita',
  trainer: 'Entrenador',
  client: 'Cliente',
  service: 'Servicio',
  bono: 'Bono',
  startsAt: 'Inicio',
  endsAt: 'Fin',
  location: 'Lugar',
  locationPlaceholder: 'Sala o estudio',
  status: 'Estado',
  statusPending: 'Pendiente',
  statusConfirmed: 'Confirmada',
  statusCompleted: 'Realizada',
  statusCancelled: 'Anulada',
  singleSession: 'Sesión suelta',
  settingsTitle: 'Reserva',
  cutoffTime: 'Hora límite del día anterior',
  defaultLocation: 'Lugar por defecto',
  schedulesTitle: 'Horarios de entrenadores',
  newSchedule: 'Nuevo horario',
  weekday: 'Día',
  startTime: 'Inicio',
  endTime: 'Fin',
  weekday1: 'Lunes',
  weekday2: 'Martes',
  weekday3: 'Miércoles',
  weekday4: 'Jueves',
  weekday5: 'Viernes',
  weekday6: 'Sábado',
  weekday7: 'Domingo',
  emptySchedules: 'Sin horarios',
  edit: 'Editar',
  errorRequired: 'Completa los campos obligatorios.',
  errorBonoRequired: 'Este servicio requiere un bono contratado.',
  errorSave: 'No se ha podido guardar la cita.',
  errorCutoff: 'Fuera de plazo o el hueco no está disponible.',
  errorSlotTaken: 'Ese hueco ya está ocupado.',
  errorOneAppointment: 'El cliente ya tiene una cita activa.',
  errorNotBookable: 'Este servicio no se puede reservar así.',
  errorExpiredBono: 'El bono está caducado.',
  errorNoSessions: 'No quedan sesiones en el bono.',
  errorInvalid: 'No se puede actualizar esta cita.',
  categoryPersonal: 'Entrenamiento personal',
  categoryHipopresivos: 'Hipopresivos',
  categoryMasaje: 'Masaje',
} as const;

export const BOOKING_ERROR_LITERALS: Record<string, string> = {
  [BOOKING_ERROR_CODES.cutoff]: CALENDAR_LITERALS.errorCutoff,
  [BOOKING_ERROR_CODES.slotTaken]: CALENDAR_LITERALS.errorSlotTaken,
  [BOOKING_ERROR_CODES.oneAppointment]: CALENDAR_LITERALS.errorOneAppointment,
  [BOOKING_ERROR_CODES.serviceNotBookable]: CALENDAR_LITERALS.errorNotBookable,
  [BOOKING_ERROR_CODES.bonoRequired]: CALENDAR_LITERALS.errorBonoRequired,
  [BOOKING_ERROR_CODES.expiredBono]: CALENDAR_LITERALS.errorExpiredBono,
  [BOOKING_ERROR_CODES.noSessions]: CALENDAR_LITERALS.errorNoSessions,
  [BOOKING_ERROR_CODES.invalidStatus]: CALENDAR_LITERALS.errorInvalid,
};
