import { BOOKING_ERROR_CODES } from '../../core/api-business.error';

export const CALENDAR_LITERALS = {
  title: 'Calendario',
  subtitle: 'Bonafit hoy: citas y huecos',
  todayTitle: 'Hoy',
  emptyToday: 'No hay citas para hoy.',
  moreActions: 'Más acciones',
  loggedAs: 'Sesión',
  week: 'Semana',
  day: 'Día',
  viewLabel: 'Vista del calendario',
  allTrainers: 'Todos',
  trainerFilter: 'Filtrar por entrenador',
  dayPrev: 'Anterior',
  dayNext: 'Siguiente',
  dayToday: 'Hoy',
  newAppointment: 'Nueva cita',
  editAppointment: 'Editar cita',
  save: 'Guardar',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  complete: 'Marcar realizada',
  cancelAppointment: 'Anular cita',
  closeEditor: 'Cerrar',
  viewClient: 'Ver ficha',
  confirmLeaveTitle: 'Salir a la ficha',
  confirmLeaveMessage: 'Hay cambios sin guardar en la cita. Si sales, se perderán.',
  confirmLeaveConfirm: 'Ir a la ficha',
  confirmCancelTitle: 'Anular cita',
  confirmCancelMessage: 'La cita pasará a anulada.',
  confirmCompleteTitle: 'Marcar realizada',
  confirmCompleteMessage: 'La cita pasará a realizada.',
  saved: 'Cita guardada.',
  trainer: 'Entrenador',
  client: 'Cliente',
  service: 'Servicio',
  bono: 'Bono',
  startsAt: 'Inicio',
  endsAt: 'Fin',
  location: 'Lugar',
  locationPlaceholder: 'Sala o estudio',
  sessionNotes: 'Nota de sesión',
  status: 'Estado',
  statusPending: 'Pendiente',
  statusConfirmed: 'Confirmada',
  statusCompleted: 'Realizada',
  statusCancelled: 'Anulada',
  gift: 'Regalo',
  singleSession: 'Sesión suelta',
  settingsTitle: 'Reserva',
  cutoffTime: 'Hora límite del día anterior',
  defaultLocation: 'Lugar por defecto',
  errorRequired: 'Completa los campos obligatorios.',
  errorLoad: 'No se ha podido cargar el calendario.',
  errorBonoRequired: 'Este servicio requiere un bono contratado.',
  errorSave: 'No se ha podido guardar la cita.',
  errorServiceInactive: 'Este servicio no está activo.',
  errorCutoff: 'Fuera de plazo o el hueco no está disponible.',
  errorSlotTaken: 'Ese hueco ya está ocupado.',
  errorOneAppointment: 'El cliente ya tiene una cita activa.',
  errorNotBookable: 'Este servicio no se puede reservar así.',
  errorExpiredBono: 'El bono está caducado.',
  errorNoSessions: 'No quedan sesiones en el bono.',
  errorInvalid: 'No se puede actualizar esta cita.',
  categoryPersonal: 'Entrenamiento personal',
  categoryHipopresivos: 'Hipopresivos',
  categoryMasaje: 'Masaje',
} as const;

export const BOOKING_ERROR_LITERALS: Record<string, string> = {
  [BOOKING_ERROR_CODES.cutoff]: CALENDAR_LITERALS.errorCutoff,
  [BOOKING_ERROR_CODES.slotTaken]: CALENDAR_LITERALS.errorSlotTaken,
  [BOOKING_ERROR_CODES.oneAppointment]: CALENDAR_LITERALS.errorOneAppointment,
  [BOOKING_ERROR_CODES.serviceNotBookable]: CALENDAR_LITERALS.errorNotBookable,
  [BOOKING_ERROR_CODES.bonoRequired]: CALENDAR_LITERALS.errorBonoRequired,
  [BOOKING_ERROR_CODES.expiredBono]: CALENDAR_LITERALS.errorExpiredBono,
  [BOOKING_ERROR_CODES.noSessions]: CALENDAR_LITERALS.errorNoSessions,
  [BOOKING_ERROR_CODES.invalidStatus]: CALENDAR_LITERALS.errorInvalid,
  [BOOKING_ERROR_CODES.serviceInactive]: CALENDAR_LITERALS.errorServiceInactive,
};
