export const SCHEDULES_LITERALS = {
  title: 'Horarios',
  subtitle: 'Franjas semanales en las que cada entrenador puede atender',
  newSchedule: 'Nueva franja',
  trainer: 'Entrenador',
  allTrainers: 'Todos los entrenadores',
  weekday: 'Día',
  startTime: 'Inicio',
  endTime: 'Fin',
  weekday1: 'Lunes',
  weekday2: 'Martes',
  weekday3: 'Miércoles',
  weekday4: 'Jueves',
  weekday5: 'Viernes',
  weekday6: 'Sábado',
  weekday7: 'Domingo',
  empty: 'Sin horarios',
  emptyTitle: 'Todavía no hay franjas',
  edit: 'Editar',
  delete: 'Eliminar',
  save: 'Guardar',
  cancel: 'Cancelar',
  saved: 'Horario guardado.',
  deleted: 'Horario eliminado.',
  confirmDeleteTitle: 'Eliminar horario',
  confirmDeleteMessage: 'Se eliminará esta franja de entrenador.',
  errorRequired: 'Completa los campos obligatorios.',
  errorInvalid: 'La hora de inicio debe ser anterior a la de fin.',
  errorTaken: 'Esa franja ya existe para este entrenador.',
  errorSave: 'No se ha podido guardar el horario.',
  errorLoad: 'No se ha podido cargar los horarios.',
} as const;
