import { ServiceCategory } from '../../models/service.dto';

export const SERVICES_LITERALS = {
  title: 'Servicios y bonos',
  subtitle: 'Catálogo comercial del estudio',
  newService: 'Nuevo servicio',
  newBono: 'Nuevo bono',
  edit: 'Editar',
  delete: 'Eliminar',
  save: 'Guardar',
  saved: 'Guardado.',
  cancel: 'Cancelar',
  emptyServices: 'Sin servicios',
  emptyBonos: 'Este servicio no tiene bonos',
  name: 'Nombre',
  category: 'Categoría',
  allowsSingleSession: 'Permite sesión suelta',
  bookableByClient: 'Reservable por el cliente',
  active: 'Activo',
  durationMinutes: 'Duración (minutos)',
  singleSessionPrice: 'Precio sesión suelta',
  sessionCount: 'Sesiones',
  price: 'Precio',
  description: 'Descripción',
  bonosTitle: 'Bonos del servicio',
  serviceEditor: 'Servicio',
  bonoEditor: 'Bono',
  yes: 'Sí',
  no: 'No',
  errorRequired: 'Completa los campos obligatorios.',
  errorSave: 'No se ha podido guardar.',
  confirmDeleteServiceTitle: 'Eliminar servicio',
  confirmDeleteServiceMessage: 'Se eliminará el servicio y sus bonos.',
  confirmDeleteBonoTitle: 'Eliminar bono',
  confirmDeleteBonoMessage: 'Se eliminará este bono del catálogo.',
  deleted: 'Eliminado.',
  search: 'Buscar',
  searchPlaceholder: 'Nombre del servicio',
} as const;

export const SERVICE_CATEGORY_LABELS: Record<ServiceCategory, string> = {
  'entrenamiento-personal': 'Entrenamiento personal',
  hipopresivos: 'Hipopresivos',
  masaje: 'Masaje',
};
