export const SERVICES_LITERALS = {
  title: 'Servicios y bonos',
  subtitle: 'Lo que ofreces: duración, reserva y packs de sesiones',
  emptyServicesTitle: 'Todavía no hay servicios',
  newService: 'Nuevo servicio',
  newBono: 'Nuevo bono',
  edit: 'Editar',
  delete: 'Eliminar',
  save: 'Guardar',
  saved: 'Guardado.',
  cancel: 'Cancelar',
  emptyServices: 'Sin servicios',
  emptyBonos: 'Este servicio no tiene bonos',
  kind: 'Tipo',
  kindService: 'Servicio',
  kindBono: 'Bono',
  name: 'Nombre',
  allowsSingleSession: 'Permite sesión suelta',
  bookableByClient: 'Reservable por el cliente',
  active: 'Activo',
  durationMinutes: 'Duración (minutos)',
  sessionCount: 'Sesiones',
  price: 'Precio',
  description: 'Descripción',
  bonosTitle: 'Bonos del servicio',
  serviceEditor: 'Servicio',
  bonoEditor: 'Bono',
  yes: 'Sí',
  no: 'No',
  errorRequired: 'Completa los campos obligatorios.',
  errorSave: 'No se ha podido guardar.',
  confirmDeleteServiceTitle: 'Eliminar servicio',
  confirmDeleteServiceMessage: 'Se eliminará el servicio. Primero debes eliminar sus bonos.',
  confirmDeleteBonoTitle: 'Eliminar bono',
  confirmDeleteBonoMessage: 'Se eliminará este bono del catálogo.',
  deleted: 'Eliminado.',
  errorAssigned: 'No se puede eliminar: hay citas, bonos o está asignado a un cliente.',
  search: 'Buscar',
  searchPlaceholder: 'Nombre del servicio o bono',
  sharesSessionPool: 'Comparte bono de sesiones',
  forcesSingleSession: 'Fuerza sesión suelta',
} as const;
