export const CATALOGO_LITERALS = {
  title: 'Catálogo',
  subtitle: 'Packs y sesiones sueltas que puedes contratar en el estudio',
  emptyTitle: 'Nada en el catálogo ahora mismo',
  loading: 'Cargando el catálogo…',
  loadError: 'No se pudo cargar el catálogo.',
  noSession: 'No hay un cliente asociado a esta sesión.',
  empty: 'No hay ofertas disponibles.',
  service: 'Servicio',
  offer: 'Oferta',
  sessions: 'Sesiones',
  price: 'Precio',
  contract: 'Contratar',
  contracted: 'Bono contratado.',
  contractError: 'No se pudo completar la contratación.',
  confirmContractTitle: 'Contratar bono',
  confirmContractMessage: 'Se contratará este bono.',
} as const;
