export const FORMS_LITERALS = {
  title: 'Formularios y encuestas',
  subtitle: 'Plantillas para el estudio y respuestas de tus clientes',
  emptyTitle: 'Todavía no hay formularios',
  search: 'Buscar',
  searchPlaceholder: 'Título o descripción',
  newForm: 'Nuevo formulario',
  edit: 'Editar',
  delete: 'Eliminar',
  empty: 'Sin formularios',
  formTitle: 'Título',
  description: 'Descripción',
  questions: 'Preguntas',
  questionCount: 'Preguntas',
  assignmentCount: 'Envíos',
  save: 'Guardar',
  back: 'Volver al listado',
  fichaTitle: 'Formulario',
  fichaNewTitle: 'Nuevo formulario',
  templateSection: 'Plantilla',
  questionsSection: 'Preguntas',
  addQuestion: 'Añadir pregunta',
  prompt: 'Pregunta',
  type: 'Tipo',
  required: 'Obligatoria',
  typeText: 'Texto largo',
  typeShortText: 'Texto corto',
  typeFullName: 'Nombre completo',
  typeEmail: 'Email',
  typePhone: 'Teléfono',
  typeDate: 'Fecha',
  typeNumber: 'Número',
  typeAddress: 'Dirección',
  typeYesNo: 'Sí / No',
  typeDropdown: 'Lista desplegable',
  typeSingleChoice: 'Opción única',
  typeMultipleChoice: 'Varias opciones',
  typeRanking: 'Ordenación',
  typeTerms: 'Condiciones',
  firstName: 'Nombre',
  lastName: 'Apellidos',
  options: 'Opciones',
  addOption: 'Añadir opción',
  optionLabel: 'Opción',
  remove: 'Quitar',
  moveUp: 'Subir',
  moveDown: 'Bajar',
  assignSection: 'Enviar a clientes',
  assignHint: 'Guarda el formulario para poder enviarlo.',
  assignAction: 'Enviar',
  select: 'Seleccionar',
  unselect: 'Quitar',
  alreadyPending: 'Pendiente',
  emptyClients: 'Sin clientes',
  assignedFeedback: 'Formulario enviado a los clientes seleccionados.',
  assignedNone: 'Los clientes seleccionados ya tienen este formulario pendiente.',
  responsesSection: 'Respuestas',
  emptyAssignments: 'Todavía no hay envíos',
  client: 'Cliente',
  status: 'Estado',
  statusPending: 'Pendiente',
  statusCompleted: 'Completado',
  assignedAt: 'Enviado',
  submittedAt: 'Respondido',
  view: 'Ver',
  answersTitle: 'Respuestas del cliente',
  emptyAnswer: 'Sin respuesta',
  yes: 'Sí',
  no: 'No',
  closeAnswers: 'Cerrar',
  errorRequired: 'Completa el título y al menos una pregunta.',
  errorQuestion: 'Cada pregunta necesita enunciado. Las de opciones, al menos dos opciones.',
  errorLoad: 'No se ha podido cargar el formulario.',
  errorSave: 'No se ha podido guardar el formulario.',
  errorAssign: 'No se ha podido enviar el formulario.',
  requiredError: 'Completa las preguntas obligatorias.',
  preview: 'Vista previa',
  previewBanner: 'Vista previa · así lo verá el cliente. No se guardan respuestas.',
  previewSubmit: 'Enviar',
  previewSubmitted: 'En un envío real se guardarían las respuestas.',
  closePreview: 'Cerrar',
  confirmDeleteTitle: 'Eliminar formulario',
  confirmDeleteMessage: 'Se eliminará este formulario y no se puede deshacer.',
  deleted: 'Formulario eliminado.',
  tabTemplate: 'Plantilla',
  tabAssign: 'Asignación',
  tabResponses: 'Respuestas',
  clientSearch: 'Buscar cliente',
  clientSearchPlaceholder: 'Nombre del cliente',
} as const;
